Book-appointment_back-end: Dev
jahongiry/book-appointment_back-end pull request #24
Opened 2022-11-08 13:17 UTC by jahongiry

## In this PR, we have done the following requirements:
- The user logs in to the website, only by typing the username
- In the navigation panel, the user can see links to:
"Reserve" form.
"My reservations".
"Add cars that you selected as a theme" (the link is visible to everybody).
- On the main page, the user can see a [list of motorcycles/doctors/classes/items that you selected as a theme](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005577).
- When the user selects a specific item, they can see the [details page](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005579) with its full description (skip the "Rotate image" button).
- On the details page, the user can click the "Reserve" button (in the design you can see the "Configure" button - please replace it with the "Reserve" button).
- When the user clicks the "Add item" link in the navigation panel they can see a form for adding a new item.
**Team: @nottherealalanturing @myelin0 @jahongiry @Zelalem1222**
Front end pull request link: https://github.com/jahongiry/book-appointment_front-end/pull/10

2022-11-08 16:21 UTC, Meltrust requested changes
Hi @jahongiry,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  API is working ✔️ 
-  Good readme ✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Suggested Changes ♻️
_Check the comments under the review._

You can use as many of my suggestions as you want.  If there is anything you would like to skip - feel free to do that.  However, I strongly recommend you take them into account as they can make your code better.


Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2022-11-08 16:21 UTC, Meltrust commented on README.md
> +- To run tests, Run the following command on your terminal
- [ ] As per your instructions, you are using Rspec, but the "test" folder still exists.  Kindly consider deleting that folder if you are not using it. 👍

2022-11-09 20:05 UTC, myelin0 commented on README.md
> +# BOOK_APPOINTMENT-BACK-END
Thank you for this suggestion. We added the swagger docs screenshot.:ok_hand:

2022-11-09 20:06 UTC, myelin0 commented on README.md
> +We hope this helps you find your way around our API.
Thanks! Documentation is now added.:+1:

2022-11-09 21:25 UTC, Meltrust requested changes
## Kindly go to the [frontend PR](https://github.com/jahongiry/book-appointment_front-end/pull/10) to view the review results and the review comments.

Hi @jahongiry ,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  App is working well✔️ 
-  Readme has been corrected ✔️
-  All the backend review requests have been implemented ✔️ 
-  Documentation has been added to the API ✔️ 
-  Nice work ✔️  

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Suggested Changes ♻️


You can use as many of my suggestions as you want.  If there is anything you would like to skip - feel free to do that.  However, I strongly recommend you take them into account as they can make your code better.


Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2022-11-09 21:42 UTC, Meltrust approved these changes
#### Hi @jahongiry,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight


   - Tests are passing✔️
   - App is working well✔️
   - Readme has been corrected ✔️
   - All the backend review requests have been implemented ✔️
   - Documentation has been added to the API ✔️
   - Superb job getting this far, congratulations 💪  ✔️✔️✔️✔️✔️✔️✔️


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

You can use as many of my suggestions as you want.  If there is anything you would like to skip - feel free to do that.  However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏


------

2022-11-10 07:12 UTC, merged